<a href="https://colab.research.google.com/github/SeEun-Kwon/data_analysis/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. pandas, dataframe, series가 무엇인가**

In [ ]:
# 1. Pandas: 데이터 조작에 특화된 파이썬 라이브러리
# Q. excel 대신 pandas 쓰는 이유
# - pandas 같은 프로그래밍 기반 도구를 사용하면 데이터처리 자동화 가능 -> 큰 데이터셋 다루기 유용
# - 파이썬 생태계의 일부에 속하여 다른 데이터 과학, 머신 러닝 라이브러리와 통합이 용이
# - 복잡한 데이터 조작하기 훨씬 편리

import pandas as pd

In [ ]:
print(pd.__version__)

2.1.4

In [ ]:
# 2. Series: 1차원 데이터(정수, 실수, 문자열 등), list로 만듦

temp = pd.Series([1, 2, 3])
temp2 = pd.Series([1, 2, 3], index=['Jan', 'Feb', 'Mar']) # index 지정
temp

0    1
1    2
2    3
dtype: int64

In [ ]:
temp2['Jan']
# temp2['May']  # 존재하지 않는 index 접근 시도 시 에러

1

In [ ]:
# 3. Dataframe: 2차원 배열(series들로 구성)

data_frame = pd.read_csv('friend_list.csv')

In [ ]:
# dataframe의 기능
data_frame.head()
data_frame.head(2)
data_frame.tail()
type(data_frame.name)

pandas.core.series.Series

In [ ]:
s1 = pd.core.series.Series([1, 2, 3])
s2 = pd.core.series.Series(['one', 'two', 'three'])
pd.DataFrame(data=dict(num=s1, word=s2))

   num   word
0    1    one
1    2    two
2    3  three

# **2. 파일에서 데이터 불러오기**  
- skiprows, nrows, sep, index_col, set_index  
- describe, info, head, tail, values, index, columns, shape  
- min, max, nlargest, mean, sum, count, unique, nunique

In [ ]:
# !conda list | grep pandas
# 강의에선 pandas 다운받으라고 하지만 구글 코랩 쓰기 때문에 다운 필요 없음
# 바로 import 가능함

import pandas as pd

- 기본 파일 불러오기

In [ ]:
# csv: comma seperated value
df = pd.read_csv('friend_list.csv')
df        # 모든 데이터
df.head() # top 5
df.tail() # bottom 5

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [ ]:
df = pd.read_csv('friend_list.txt')
# txt도 csv로 불러오는 이유
# csv 파일은 정보가 콤마로 구분된 텍스트 파일, 엑셀은 이런 파일을 콤마를 기준으로 데이터 분리해 cell 단위로 저장(바이너리 기반 파일)
# delimiter=none 이면 sep의 기본값 sep=','로 처리됨

df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

  - 구분자가 다른 파일 불러오기

In [ ]:
df_wrong = pd.read_csv('friend_list_tab.txt')
df_wrong

         name\tage\tjob
0     John\t20\tstudent
1  Jenny\t30\tdeveloper
2     Nate\t30\tteacher
3    Julia\t40\tdentist
4    Brian\t45\tmanager
5     Chris\t25\tintern

In [ ]:
# delimiter라는 parameter 필요
df = pd.read_csv('friend_list_tab.txt', delimiter = '\t')
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

  - header가 없을 때

In [ ]:
df = pd.read_csv('friend_list_no_head.csv')
df

    John  20    student
0  Jenny  30  developer
1   Nate  30    teacher
2  Julia  40    dentist
3  Brian  45    manager
4  Chris  25     intern

In [ ]:
df = pd.read_csv('friend_list_no_head.csv', header = None)
df

       0   1          2
0   John  20    student
1  Jenny  30  developer
2   Nate  30    teacher
3  Julia  40    dentist
4  Brian  45    manager
5  Chris  25     intern

In [ ]:
df1 = pd.read_csv('friend_list_no_head.csv', header = None, names=['name', 'age', 'job'])
df1

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [ ]:
df.columns = ['name', 'age', 'job']
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

# **3. 데이터프레임 생성하기**

In [ ]:
import pandas as pd

1. dictionary로 생성

In [ ]:
friend_dict_list = [
    {'name': 'John', 'age': 25, 'job': 'student'},
    {'name': 'Nate', 'age': 30, 'job': 'teacher'}
]
df = pd.DataFrame(friend_dict_list)
df.head()
# python 3.6이전에선 key값의 순서 보장x
# python 3.7 부터는 dictionary가 순서 기억

   name  age      job
0  John   25  student
1  Nate   30  teacher

In [ ]:
import sys
sys.version

'3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]'

* dict 순서 정하는 방법

In [ ]:
df = df[['name', 'age', 'job']]
df.head()

   name  age      job
0  John   25  student
1  Nate   30  teacher

In [ ]:
from collections import OrderedDict

friend_ordered_dict = OrderedDict(
    [
        ('name', ['John', 'Nate']),
        ('age', [25, 30]),
        ('job', ['student', 'teacher'])
    ]
)
df = pd.DataFrame.from_dict(friend_ordered_dict)
df.head()
# list를 OrderedDict 함수 인자로 넣어 초기화하는 형식
# 키, 값 쌍의 순서가 중요하기 때문에 immutable한 tuple 사용
# 소괄호는 tuple, 중괄호는 dict, 대괄호는 list

   name  age      job
0  John   25  student
1  Nate   30  teacher

2. list로 생성

In [ ]:
friend_list = [
    ['John', 20, 'student'],
    ['Nate', 30, 'teacher']
]
column_name = ['name', 'age', 'job']
df = pd.DataFrame.from_records(friend_list, columns=column_name)
df.head()

# 행 기준으로 정보 입력

   name  age      job
0  John   20  student
1  Nate   30  teacher

In [ ]:
friend_list = [
    ['name', ['John', 'Nate']],
    ['age', [20, 30]],
    ['job', ['student', 'teacher']]
]
df = pd.DataFrame.from_dict(dict(friend_list))
df.head()

# 열 기준으로 정보 입력

   name  age      job
0  John   20  student
1  Nate   30  teacher

# **4. 데이터프레임 파일로 저장하기**  
csv, txt, excel로 저장

In [ ]:
import pandas as pd

In [ ]:
friends = [
    {'name': 'John', 'age': 20, 'job': 'student'},
    {'name': 'Jenny', 'age': 30, 'job': None},
    {'name': 'Nate', 'age': 30, 'job': 'teacher'}
]
df = pd.DataFrame(friends)
# df = df[['name', 'age', 'job']]
df

    name  age      job
0   John   20  student
1  Jenny   30     None
2   Nate   30  teacher

In [ ]:
df.to_csv('friends.csv') # default: index=True, header=True

In [ ]:
df.to_csv('friends.csv', index=False, header=True) # row index 사라짐

In [ ]:
df.to_csv('friends.csv', index=False, header=False) # row index, header 사라짐

In [ ]:
# none value 변환하여 빈 값이란 걸 명시
df.to_csv('friends.csv', index=False, na_rep='-')

# **5. 데이터프레임 행, 열 선택 및 필터링 하기**

In [ ]:
import pandas as pd

In [ ]:
friend_list = [
    ['name', ['John', 'Jenny', 'Nate']],
    ['age', [20, 30, 30]],
    ['job', ['student', 'developer', 'teacher']]
]
df = pd.DataFrame.from_dict(dict(friend_list))
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher

**행 열 선택**

- list 성질 이용

In [ ]:
df[1:3] # 이렇게만 하면 원정보 변화 없음

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher

In [ ]:
df = df[1:3] # 원정보까지 수정

In [ ]:
df

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher

In [ ]:
# df 원상복구
df = pd.DataFrame.from_dict(dict(friend_list))
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher

- loc함수 사용 (label기반 indexing)

In [ ]:
df.loc[[0, 2]]

   name  age      job
0  John   20  student
2  Nate   30  teacher

In [ ]:
df = df.loc[[0, 2]]
df

   name  age      job
0  John   20  student
2  Nate   30  teacher

- column condition 이용

In [ ]:
df[df.age > 25]

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher

In [ ]:
df.query('age>25')  # query 함수 추가 공부하면 좋을 듯

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher

In [ ]:
df[ (df.age > 25) & (df.name == 'Nate') ]

   name  age      job
2  Nate   30  teacher

**filter column**

In [ ]:
friend_list = [
    ['John', 20, 'student'],
    ['Jenny', 30, 'developer'],
    ['Nate', 30, 'teacher']
]
df = pd.DataFrame.from_records(friend_list) # dictionary만 from_dict 이용
df

       0   1          2
0   John  20    student
1  Jenny  30  developer
2   Nate  30    teacher

- index 이용 (정수 기반 indexing)

In [ ]:
df.iloc[:, 0:2]

df.iloc[0:2, :]

    name  age        job
0   John   20    student
1  Jenny   30  developer

In [ ]:
df = pd.read_csv('friend_list_no_head.csv', header=None, names=['name', 'age', 'job'])
# df = pd.read_csv('friend_list.csv') 와 동일
df
# parameter - names: column names 지정 header: 첫 행이 열이름인지 데이터인지 구분

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

- column name 이용

In [ ]:
df_filtered = df[['name', 'age']]
df_filtered

    name  age
0   John   20
1  Jenny   30
2   Nate   30
3  Julia   40
4  Brian   45
5  Chris   25

- filter 함수 이용

In [ ]:
df.filter(items=['age', 'job'])

   age        job
0   20    student
1   30  developer
2   30    teacher
3   40    dentist
4   45    manager
5   25     intern

In [ ]:
df.filter(like='a', axis=1) # axis=0: row, axis=1: column
# column이름에 a 들어간 것만 filter

    name  age
0   John   20
1  Jenny   30
2   Nate   30
3  Julia   40
4  Brian   45
5  Chris   25

In [ ]:
df.filter(regex='b$', axis=1) # b로 끝나는 column만 filter

         job
0    student
1  developer
2    teacher
3    dentist
4    manager
5     intern

# **6. 행, 열 생성 및 수정하기**

In [ ]:
import pandas as pd

In [ ]:
df.loc[6] = ['Jack', 30, 'developer']

In [ ]:
friend_dict_list = [
    {'name': 'John', 'age': 15, 'job': 'student'},
    {'name': 'Jenny', 'age': 30, 'job': 'developer'},
    {'name': 'Nate', 'age': 30, 'job': 'teacher'}
]
df = pd.DataFrame(friend_dict_list, columns = ['name', 'age', 'job'])
df

    name  age        job
0   John   15    student
1  Jenny   30  developer
2   Nate   30    teacher

- column 생성

In [ ]:
df['salary'] = 0
df

    name  age        job  salary
0   John   15    student       0
1  Jenny   30  developer       0
2   Nate   30    teacher       0

In [ ]:
# np.where함수로 job=student인 경우, 아닌경우에 따라 salary 항목 채우기
import numpy as np
df['salary'] = np.where(df['job'] != 'student', 'yes', 'no')
df

    name  age        job salary
0   John   15    student     no
1  Jenny   30  developer    yes
2   Nate   30    teacher    yes

In [ ]:
# 예제를 위한 데이터프레임 수정
friend_dict_list = [
    {'name': 'John', 'midterm': 95, 'final': 85},
    {'name': 'Jenny', 'midterm': 85, 'final': 80},
    {'name': 'Nate', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(friend_dict_list, columns = ['name', 'midterm', 'final'])
df

    name  midterm  final
0   John       95     85
1  Jenny       85     80
2   Nate       10     30

In [ ]:
df['total'] = df['midterm'] + df['final']
df['average'] = df['total'] / 2
df

    name  midterm  final  total  average
0   John       95     85    180     90.0
1  Jenny       85     80    165     82.5
2   Nate       10     30     40     20.0

In [ ]:
grades = []

for row in df['average']:
    if row >= 90:
        grades.append('A')
    elif row >= 80:
        grades.append('B')
    else:
        grades.append('F')

df['grade'] = grades
df

    name  midterm  final  total  average grade
0   John       95     85    180     90.0     A
1  Jenny       85     80    165     82.5     B
2   Nate       10     30     40     20.0     F

In [ ]:
# for i in range(5):
#     print(i)

list = ['A', 'B', 'C', 'D', 'E']
for i in list:
    print(i)

A
B
C
D
E

In [ ]:
def pass_or_fail(row):
    if row != 'F':
        return "Pass"
    else:
        return "Fail"

df.grade = df.grade.apply(pass_or_fail) # grade에 pass_or_fail 함수 적용
df
# apply는 벡터화된 연산 수행 -> row, column에 대해 반복하는 작업을 효율적으로 처리 가능
# 큰 데이터셋에서 apply가 for보다 훨씬 빠르게 데이터 처리

    name  midterm  final  total  average grade
0   John       95     85    180     90.0  Pass
1  Jenny       85     80    165     82.5  Pass
2   Nate       10     30     40     20.0  Pass

In [ ]:
date_list = [
    {'yyyy-mm-dd': '2000-06-27'},
    {'yyyy-mm-dd': '2007-10-27'}
]
df = pd.DataFrame(date_list, columns = ['yyyy-mm-dd'])
df

   yyyy-mm-dd
0  2000-06-27
1  2007-10-27

In [ ]:
def extract_year(row):
    return row.split('-')[0]

df['year'] = df['yyyy-mm-dd'].apply(extract_year)
df.head()

   yyyy-mm-dd  year
0  2000-06-27  2000
1  2007-10-27  2007

- row 생성

In [ ]:
# 데이터프레임 초기화
friend_dict_list = [
    {'name': 'John', 'midterm': 95, 'final': 85},
    {'name': 'Jenny', 'midterm': 85, 'final': 80},
    {'name': 'Nate', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(friend_dict_list, columns = ['name', 'midterm', 'final'])
df

    name  midterm  final
0   John       95     85
1  Jenny       85     80
2   Nate       10     30

In [ ]:
df2 = pd.DataFrame([
    ['Ben', 50, 50]
], columns=['name', 'midterm', 'final'])
df2

  name  midterm  final
0  Ben       50     50

In [ ]:
# df.append(df2, ignore_index=True)    # pandas의 append는 사용 중단됨/ 기본 list의 append는 사용 가능
df = pd.concat([df,df2], ignore_index=True)
df

    name  midterm  final
0   John       95     85
1  Jenny       85     80
2   Nate       10     30
3    Ben       50     50
4    Ben       50     50
5    Ben       50     50

In [ ]:
df = df.drop(df.index[4:6])
df

    name  midterm  final
0   John       95     85
1  Jenny       85     80
2   Nate       10     30
3    Ben       50     50

# **7. 데이터 그룹 만들기**

In [ ]:
import pandas as pd

In [ ]:
student_list = [
    {'name': 'John', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Nate', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Abraham', 'major': "Physics", 'sex': "male"},
    {'name': 'Brian', 'major': "Psychology", 'sex': "male"},
    {'name': 'Janny', 'major': "Economics", 'sex': "female"},
    {'name': 'Yuna', 'major': "Economics", 'sex': "female"},
    {'name': 'Jeniffer', 'major': "Computer Science", 'sex': "female"},
    {'name': 'Edward', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Zara', 'major': "Psychology", 'sex': "female"},
    {'name': 'Wendy', 'major': "Economics", 'sex': "female"},
    {'name': 'Sera', 'major': "Psychology", 'sex': "female"}
]
df = pd.DataFrame(student_list, columns = ['name', 'major', 'sex'])
df

        name             major     sex
0       John  Computer Science    male
1       Nate  Computer Science    male
2    Abraham           Physics    male
3      Brian        Psychology    male
4      Janny         Economics  female
5       Yuna         Economics  female
6   Jeniffer  Computer Science  female
7     Edward  Computer Science    male
8       Zara        Psychology  female
9      Wendy         Economics  female
10      Sera        Psychology  female

In [ ]:
# groupby이용하여 학과별로 몇 명 있는지 확인
groupby_major = df.groupby('major')   # 각 그룹('학과이름')에 대해 서브 데이터프레임 생성
groupby_major         # 그룹화된 데이터를 관리하는 객체를 반환, 메모리 주소만 출력됨
groupby_major.groups  # groups 속성을 사용
                      # : DataFrameGroupBy 객체에서 제공되는 속성(attribute)
                      # : 각 그룹이과 그룹에 속한 index를 dict 형태로 출력
# Person이라는 class에 name, age, address가 있을 때,
# 이를 기반으로 Alice, Bob 같은 instance(객체)를 만들 수 있음
# 객체의 속성은 name, age, address
# 즉, groupby함수로 groupby_major라는 객체 생성, 객체의 groups라는 속성을 확인한 것

{'Computer Science': [0, 1, 6, 7], 'Economics': [4, 5, 9], 'Physics': [2], 'Psychology': [3, 8, 10]}

In [ ]:
for name, group in groupby_major:
    print(name + ": " + str(len(group)))
    print(group)
    print()

       name             major     sex
0      John  Computer Science    male
1      Nate  Computer Science    male
6  Jeniffer  Computer Science  female
7    Edward  Computer Science    male

    name      major     sex
4  Janny  Economics  female
5   Yuna  Economics  female
9  Wendy  Economics  female

      name    major   sex
2  Abraham  Physics  male

     name       major     sex
3   Brian  Psychology    male
8    Zara  Psychology  female
10   Sera  Psychology  female

In [ ]:
df_major_cnt = pd.DataFrame({'count': groupby_major.size()}).reset_index()
df_major_cnt
# major는 column name으로 size() 호출 불가
# size() 메서드는 DataFrameGroupBy 객체에서 호출되어 각 그룹의 크기를 계산함
# 메서드 method는 클래스 안에 정의된 함

              major  count
0  Computer Science      4
1         Economics      3
2           Physics      1
3        Psychology      3

In [ ]:
group_sex = df.groupby('sex')
group_sex.groups

{'female': [4, 5, 6, 8, 9, 10], 'male': [0, 1, 2, 3, 7]}

In [ ]:
for name, group in group_sex:
    print(name + ": " + str(len(group)))
    print(group)
    print()

female: 6
        name             major     sex
4      Janny         Economics  female
5       Yuna         Economics  female
6   Jeniffer  Computer Science  female
8       Zara        Psychology  female
9      Wendy         Economics  female
10      Sera        Psychology  female

male: 5
      name             major   sex
0     John  Computer Science  male
1     Nate  Computer Science  male
2  Abraham           Physics  male
3    Brian        Psychology  male
7   Edward  Computer Science  male

# **8. 중복데이터 삭제하기**

In [ ]:
# 중복된 데이터 있는 dataframe 생성
student_list = [
    {'name': 'John', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Nate', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Edward', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Zara', 'major': "Psychology", 'sex': "female"},
    {'name': 'John', 'major': "Computer Science", 'sex': "male"}
]
df = pd.DataFrame(student_list, columns = ['name', 'major', 'sex'])
df

     name             major     sex
0    John  Computer Science    male
1    Nate  Computer Science    male
2  Edward  Computer Science    male
3    Zara        Psychology  female
4    John  Computer Science    male

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
df.drop_duplicates()

     name             major     sex
0    John  Computer Science    male
1    Nate  Computer Science    male
2  Edward  Computer Science    male
3    Zara        Psychology  female

In [ ]:
# 중복된 데이터 있는 dataframe 생성
student_list = [
    {'name': 'John', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Nate', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Edward', 'major': "Computer Science", 'sex': "male"},
    {'name': 'Zara', 'major': "Psychology", 'sex': "female"},
    {'name': 'Wendy', 'major': "Economics", 'sex': "female"},
    {'name': 'Nate', 'major': None, 'sex': "male"},
    {'name': 'John', 'major': "Economics", 'sex': "male"}
]
df = pd.DataFrame(student_list, columns = ['name', 'major', 'sex'])
df

     name             major     sex
0    John  Computer Science    male
1    Nate  Computer Science    male
2  Edward  Computer Science    male
3    Zara        Psychology  female
4   Wendy         Economics  female
5    Nate              None    male
6    John         Economics    male

In [ ]:
# 특정 열의 값이 같을 때 그 행 삭제하기
df.duplicated(['name'])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
dtype: bool

In [ ]:
df.drop_duplicates(['name']) # keep의 default는 first
df.drop_duplicates(['name'], keep='first')

     name             major     sex
0    John  Computer Science    male
1    Nate  Computer Science    male
2  Edward  Computer Science    male
3    Zara        Psychology  female
4   Wendy         Economics  female

In [ ]:
df.drop_duplicates(['name'], keep='last')

# **9. NaN 찾아서 다른 값으로 변경하기**

In [ ]:
school_id_list = [
    {'name': 'John', 'job': "teacher", 'age': 40},
    {'name': 'Nate', 'job': "teacher", 'age': 35},
    {'name': 'Fred', 'job': "teacher", 'age': 37},
    {'name': 'Abraham', 'job': "student", 'age': 10},
    {'name': 'Brian', 'job': "student", 'age': 12},
    {'name': 'Janny', 'job': "student", 'age': 11},
    {'name': 'Nate', 'job': "teacher", 'age': None},
    {'name': 'John', 'job': "student", 'age': None}
]
df = pd.DataFrame(school_id_list, columns = ['name', 'job', 'age'])
df

      name      job   age
0     John  teacher  40.0
1     Nate  teacher  35.0
2     Fred  teacher  37.0
3  Abraham  student  10.0
4    Brian  student  12.0
5    Janny  student  11.0
6     Nate  teacher   NaN
7     John  student   NaN

In [ ]:
df.shape   # (행, 열)

(8, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   job     8 non-null      object
 2   age     6 non-null      float64
dtypes: float64(1), object(2)
memory usage: 320.0+ bytes

In [ ]:
df.isna()

    name    job    age
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False   True
7  False  False   True

In [ ]:
df.isnull()

    name    job    age
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False   True
7  False  False   True

In [ ]:
df.age = df.age.fillna(0)
df

      name      job   age
0     John  teacher  40.0
1     Nate  teacher  30.0
2     Fred  teacher  35.0
3  Abraham  student  10.0
4    Brian  student  12.0
5    Janny  student  11.0
6     Nate  teacher   0.0
7     John  student   0.0

In [ ]:
df['age'].fillna(df.groupby('job')['age'].transform('median'), inplace=True)
df

      name      job   age
0     John  teacher  40.0
1     Nate  teacher  35.0
2     Fred  teacher  37.0
3  Abraham  student  10.0
4    Brian  student  12.0
5    Janny  student  11.0
6     Nate  teacher  37.0
7     John  student  11.0

# **10. apply 함수 활용**

In [ ]:
date_list = [
    {'yyyy-mm-dd': '2000-06-27'},
    {'yyyy-mm-dd': '2002-09-24'},
    {'yyyy-mm-dd': '2005-12-20'}
]
df = pd.DataFrame(date_list, columns = ['yyyy-mm-dd'])
df

   yyyy-mm-dd
0  2000-06-27
1  2002-09-24
2  2005-12-20

In [ ]:
def extract_year(column):
    return column.split("-")[0]
    # return column[0:2]

df['year'] = df['yyyy-mm-dd'].apply(extract_year)
df

   yyyy-mm-dd  year   age
0  2000-06-27  2000  1998
1  2002-09-24  2002  1998
2  2005-12-20  2005  1998

In [ ]:
def get_age(year, current_year):
    return current_year - int(year)

df['age'] = df['year'].apply(get_age, current_year=2018)
df

   yyyy-mm-dd  year  age
0  2000-06-27  2000   18
1  2002-09-24  2002   16
2  2005-12-20  2005   13

In [ ]:
def get_introduce(age, prefix, suffix):
    return prefix + str(age) + suffix

df['introduce'] = df['age'].apply(get_introduce, prefix="I am ", suffix=" years old")
df

   yyyy-mm-dd  year  age          introduce
0  2000-06-27  2000   18  I am 18 years old
1  2002-09-24  2002   16  I am 16 years old
2  2005-12-20  2005   13  I am 13 years old

In [ ]:
def get_introduce_2(row):
    return "I was born in "+str(row.year)+" my age is "+str(row.age)

df.introduce = df.apply(get_introduce_2, axis=1)    # axis=0: row, axis=1: column
df
# df.introduce = df['introduce']

# **11. map, applymap 함수 활용**

In [ ]:
data_list = [
    {'date': '2000-06-27'},
    {'date': '2002-09-24'},
    {'date': '2005-12-20'}
]
df = pd.DataFrame(data_list, columns = ['date'])
df

         date
0  2000-06-27
1  2002-09-24
2  2005-12-20

In [ ]:
def extract_year(date):
    return date.split('-')[0]

df['year'] = df['date'].map(extract_year)
df

# map: 주로 Series 객체에서 사용됨. 각 요소에 대해 함수를 적용하거나 값 매핑할 때 사용
# apply: Series, DataFrame 모두에서 사용됨. 더 복잡한 연산을 행이나 열 단위로 적용할 때 유

         date  year
0  2000-06-27  2000
1  2002-09-24  2002
2  2005-12-20  2005

In [ ]:
job_list = [
    {'age': 20, 'job': 'student'},
    {'age': 30, 'job': 'developer'},
    {'age': 30, 'job': 'teacher'}
]
df = pd.DataFrame(job_list)
df

   age        job
0   20    student
1   30  developer
2   30    teacher

In [ ]:
df.job = df.job.map({'student':1, 'developer':2, 'teacher':3})
df
# map함수의 장점
# - 함수를 통해 값 변경 가능
# - dictionary 직접 전달함으로써 원하는 값으로 변경 가능

   age  job
0   20    1
1   30    2
2   30    3

In [ ]:
x_y = [
    {'x': 5.5, 'y': -5.6, 'z': -1.1},
    {'x': -5.2, 'y': 5.5, 'z': -2.2},
    {'x': -1.6, 'y': -4.5, 'z': -3.3}
]
df = pd.DataFrame(x_y)
df

     x    y    z
0  5.5 -5.6 -1.1
1 -5.2  5.5 -2.2
2 -1.6 -4.5 -3.3

In [ ]:
# 모든 column에 적용할 때 applymap() 사용
import numpy as np
df = df.applymap(np.around)   # np.around: 반올림
df

<ipython-input-86-dc44239eda0a>:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(np.around)

     x    y    z
0  6.0 -6.0 -1.0
1 -5.0  6.0 -2.0
2 -2.0 -4.0 -3.0

# **12. 컬럼 내 유니크한 값 뽑아내고 갯수 확인하기**

In [ ]:
job_list = [
    {'name': 'John', 'job': "teacher"},
    {'name': 'Nate', 'job': "teacher"},
    {'name': 'Fred', 'job': "teacher"},
    {'name': 'Abraham', 'job': "student"},
    {'name': 'Brian', 'job': "student"},
    {'name': 'Janny', 'job': "developer"},
    {'name': 'Nate', 'job': "teacher"},
    {'name': 'Ian', 'job': "teacher"},
    {'name': 'Chris', 'job': "banker"},
    {'name': 'Philip', 'job': "lawyer"},
    {'name': 'Janny', 'job': "basketball player"},
    {'name': 'Gwen', 'job': "teacher"},
    {'name': 'Jessy', 'job': "student"}
]
df = pd.DataFrame(job_list, columns = ['name', 'job'])
df

       name                job
0      John            teacher
1      Nate            teacher
2      Fred            teacher
3   Abraham            student
4     Brian            student
5     Janny          developer
6      Nate            teacher
7       Ian            teacher
8     Chris             banker
9    Philip             lawyer
10    Janny  basketball player
11     Gwen            teacher
12    Jessy            student

In [ ]:
df.job.unique()

array(['teacher', 'student', 'developer', 'banker', 'lawyer',
       'basketball player'], dtype=object)

In [ ]:
df.job.value_counts()

job
teacher              6
student              3
developer            1
banker               1
lawyer               1
basketball player    1
Name: count, dtype: int64

In [ ]:
job_counts = df.job.value_counts()
job_counts_df = job_counts.reset_index()
job_counts_df

                 job  count
0            teacher      6
1            student      3
2          developer      1
3             banker      1
4             lawyer      1
5  basketball player      1

# **13. 두 개의 데이터프레임 합치기**

In [ ]:
l1 = [
    {'name': 'John', 'job': "teacher"},
    {'name': 'Nate', 'job': "student"},
    {'name': 'Fred', 'job': "developer"}
]

l2 = [
    {'name': 'Ed', 'job': "dentist"},
    {'name': 'Jack', 'job': "farmer"},
    {'name': 'Ted', 'job': "designer"}
]

l3 = [
    {'name': 'John', 'job': "teacher"},
    {'name': 'Nate', 'job': "student"},
    {'name': 'Jack', 'job': "developer"}
]

l4 = [
    {'age': 25, 'country': "U.S"},
    {'age': 30, 'country': "U.K"},
    {'age': 45, 'country': "Korea"}
]

df1 = pd.DataFrame(l1, columns = ['name', 'job'])
df2 = pd.DataFrame(l2, columns = ['name', 'job'])
df1

   name        job
0  John    teacher
1  Nate    student
2  Fred  developer

In [ ]:
df2

   name       job
0    Ed   dentist
1  Jack    farmer
2   Ted  designer

In [ ]:
# result = pd.concat([df1, df2])    # index 012012 됨
result = pd.concat([df1, df2], ignore_index=True)
# result = df1.append(df2, ignore_index=True)   # append attribute사라짐
result

   name        job
0  John    teacher
1  Nate    student
2  Fred  developer
3    Ed    dentist
4  Jack     farmer
5   Ted   designer

In [ ]:
df1 = pd.DataFrame(l3, columns = ['name', 'job'])
df2 = pd.DataFrame(l4, columns = ['age', 'country'])

In [ ]:
df1

   name        job
0  John    teacher
1  Nate    student
2  Jack  developer

In [ ]:
df2

   age country
0   25     U.S
1   30     U.K
2   45   Korea

In [ ]:
result = pd.concat([df1, df2], axis=0, ignore_index=True)
result

      0          1     2         3
0  John    teacher    Ed   dentist
1  Nate    student  Jack    farmer
2  Fred  developer   Ted  designer

In [ ]:
result = pd.concat([df1, df2], axis=1)
result

   name        job  age country
0  John    teacher   25     U.S
1  Nate    student   30     U.K
2  Jack  developer   45   Korea

In [ ]:
# 리스트는 비교하기 불편하므로 데이터프레임으로 합쳐서 비교
label = [1,2,3,4,5]
prediction = [1,2,2,4,4]

comparison = pd.DataFrame({'label': label, 'prediction': prediction})
comparison

   label  prediction
0      1           1
1      2           2
2      3           2
3      4           4
4      5           4