<a href="https://colab.research.google.com/github/SeEun-Kwon/data_analysis/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%8B%A4%EC%8A%B5_%EC%A1%B0%EC%B9%98%EC%9B%90%EC%83%81%EA%B6%8C%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 한글 깨짐 방지 코드
import sys

# Google Colab 환경에서 실행 중인지 확인
if 'google.colab' in sys.modules:
    # debconf를 Noninteractive 모드로 설정
    !echo 'debconf debconf/frontend select Noninteractive' | \
    debconf-set-selections

    !sudo apt-get -qq -y install fonts-nanum      # fonts-nanum 패키지 설치
    import matplotlib.font_manager as fm          # Matplotlib의 폰트 매니저 가져오기
    font_files = fm.findSystemFonts(fontpaths=['/usr/share/fonts/truetype/nanum'])  # 나눔 폰트의 시스템 경로 찾기
    for fpath in font_files:                       # 찾은 각 나눔 폰트를 Matplotlib 폰트 매니저에 추가
        fm.fontManager.addfont(fpath)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/24-2 데이터분석/데이터셋/세종특별자치시_조치원읍_리별_인구_현황_20221104.csv', encoding='EUC-KR')
df1.head()

    구분  세대수   남자   여자    데이터 기준일자
0  원1리  349  286  272  2022-11-04
1  원2리  104  111  114  2022-11-04
2  상1리  220  186  157  2022-11-04
3  상2리  184  165  145  2022-11-04
4   평리  316  319  291  2022-11-04

In [ ]:
df1.sort_values(by='세대수', ascending=False, inplace=True, ignore_index=True)
# df1.head(10)/

     구분   세대수    남자    여자    데이터 기준일자
0    교리  1436  1370  1374  2022-11-04
1  죽림2리  1406  2102  2129  2022-11-04
2  서창2리  1174   948   680  2022-11-04
3  침산3리  1173  1486  1577  2022-11-04
4  신안1리  1031   800   540  2022-11-04
5   남1리   984   920   689  2022-11-04
6  침산2리   965   808   563  2022-11-04
7  신안4리   937  1327  1364  2022-11-04
8  죽림1리   923  1238  1222  2022-11-04
9  신흥5리   914  1096  1137  2022-11-04

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   구분        36 non-null     object
 1   세대수       36 non-null     int64
 2   남자        36 non-null     int64
 3   여자        36 non-null     int64
 4   데이터 기준일자  36 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.5+ KB

In [ ]:
df1['구분'].unique()

array(['교리', '죽림2리', '서창2리', '침산3리', '신안1리', '남1리', '침산2리', '신안4리',
       '죽림1리', '신흥5리', '신흥6리', '신흥7리', '침산4리', '죽림4리', '서창1리', '죽림3리',
       '정리', '번암1리', '번암2리', '남2리', '신안3리', '신흥1리', '명리', '원1리', '평리',
       '신안2리', '죽림5리', '상1리', '신흥4리', '봉산1리', '침산1리', '상2리', '신흥3리',
       '원2리', '신흥2리', '봉산2리'], dtype=object)

In [ ]:
population = df1[['구분', '세대수', '데이터 기준일자']]
population.head()

     구분   세대수    데이터 기준일자
0    교리  1436  2022-11-04
1  죽림2리  1406  2022-11-04
2  서창2리  1174  2022-11-04
3  침산3리  1173  2022-11-04
4  신안1리  1031  2022-11-04

In [ ]:
def division(name):
  name = name.split('리')
  if name[0][-1].isdigit():
    return name[0][:-1]+'리'+name[0][-1]
  else:
    return name[0]+'리'+'0'

population['구분'] = population['구분'].apply(division)
population.head()

<ipython-input-210-76ebfa4f4de7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  population['구분'] = population['구분'].apply(division)

     구분   세대수    데이터 기준일자
0   교리0  1436  2022-11-04
1  죽림리2  1406  2022-11-04
2  서창리2  1174  2022-11-04
3  침산리3  1173  2022-11-04
4  신안리1  1031  2022-11-04

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/24-2 데이터분석/데이터셋/소상공인시장진흥공단_상가(상권)정보_세종_202409.csv', encoding='UTF-8')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13221 entries, 0 to 13220
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상가업소번호     13221 non-null  object
 1   상호명        13221 non-null  object
 2   지점명        446 non-null    object
 3   상권업종대분류코드  13221 non-null  object
 4   상권업종대분류명   13221 non-null  object
 5   상권업종중분류코드  13221 non-null  object
 6   상권업종중분류명   13221 non-null  object
 7   상권업종소분류코드  13221 non-null  object
 8   상권업종소분류명   13221 non-null  object
 9   표준산업분류코드   13218 non-null  object
 10  표준산업분류명    13218 non-null  object
 11  시도코드       13221 non-null  int64
 12  시도명        13221 non-null  object
 13  시군구코드      13221 non-null  int64
 14  시군구명       13221 non-null  object
 15  행정동코드      13221 non-null  int64
 16  행정동명       13221 non-null  object
 17  법정동코드      13221 non-null  int64
 18  법정동명       13221 non-null  object
 19  지번코드       13221 non-null  int64
 20  대지구분코드     13221 non-null  int64
 21  대지구분명      13221 non-null  object
 22  지번본번지      13220 non-null  float64
 23  지번부번지      4972 non-null   float64
 24  지번주소       13221 non-null  object
 25  도로명코드      13162 non-null  float64
 26  도로명        13221 non-null  object
 27  건물본번지      13162 non-null  float64
 28  건물부번지      2208 non-null   float64
 29  건물관리번호     13220 non-null  object
 30  건물명        7809 non-null   object
 31  도로명주소      13221 non-null  object
 32  구우편번호      13142 non-null  float64
 33  신우편번호      13221 non-null  int64
 34  동정보        0 non-null      float64
 35  층정보        6546 non-null   object
 36  호정보        0 non-null      float64
 37  경도         13221 non-null  float64
 38  위도         13221 non-null  float64
dtypes: float64(10), int64(7), object(22)
memory usage: 3.9+ MB

In [ ]:
jochiwon = df2.iloc[:,[1, 16, 24, 31]].groupby('행정동명').get_group('조치원읍')
jochiwon.drop(columns=['행정동명'], inplace=True)
jochiwon.head(5)

,상호명,지번주소,도로명주소
5,세종마취과,세종특별자치시 세종특별자치시 조치원읍 남리 119-12,세종특별자치시 세종특별자치시 조치원읍 새내1길 17
8,로엘라,세종특별자치시 세종특별자치시 조치원읍 원리 1-22,세종특별자치시 세종특별자치시 조치원읍 조치원7길 12
13,세종드럼뮤직학원,세종특별자치시 세종특별자치시 조치원읍 신흥리 48-2,세종특별자치시 세종특별자치시 조치원읍 충현로 91
20,부동산땅집go공인중개사사무소,세종특별자치시 세종특별자치시 조치원읍 신흥리 1-23,세종특별자치시 세종특별자치시 조치원읍 신흥샛터길 43
24,쿠헤어,세종특별자치시 세종특별자치시 조치원읍 정리 34-1,세종특별자치시 세종특별자치시 조치원읍 새내8길 17

In [ ]:
population['구분'].unique()

array(['교리0', '죽림리2', '서창리2', '침산리3', '신안리1', '남리1', '침산리2', '신안리4',
       '죽림리1', '신흥리5', '신흥리6', '신흥리7', '침산리4', '죽림리4', '서창리1', '죽림리3',
       '정리0', '번암리1', '번암리2', '남리2', '신안리3', '신흥리1', '명리0', '원리1', '평리0',
       '신안리2', '죽림리5', '상리1', '신흥리4', '봉산리1', '침산리1', '상리2', '신흥리3',
       '원리2', '신흥리2', '봉산리2'], dtype=object)

In [ ]:
def make_lee(input):
  for name in population['구분']:
    if name[:-1] in input:
      return name[:-1]

jochiwon['리'] = jochiwon['지번주소'].apply(make_lee)
jochiwon.head()

,상호명,지번주소,도로명주소,리
5,세종마취과,세종특별자치시 세종특별자치시 조치원읍 남리 119-12,세종특별자치시 세종특별자치시 조치원읍 새내1길 17,남리
8,로엘라,세종특별자치시 세종특별자치시 조치원읍 원리 1-22,세종특별자치시 세종특별자치시 조치원읍 조치원7길 12,원리
13,세종드럼뮤직학원,세종특별자치시 세종특별자치시 조치원읍 신흥리 48-2,세종특별자치시 세종특별자치시 조치원읍 충현로 91,신흥리
20,부동산땅집go공인중개사사무소,세종특별자치시 세종특별자치시 조치원읍 신흥리 1-23,세종특별자치시 세종특별자치시 조치원읍 신흥샛터길 43,신흥리
24,쿠헤어,세종특별자치시 세종특별자치시 조치원읍 정리 34-1,세종특별자치시 세종특별자치시 조치원읍 새내8길 17,정리

In [ ]:
jochiwon = jochiwon.groupby('리')

In [ ]:
jochiwon.groups.keys()

dict_keys(['교리', '남리', '명리', '번암리', '봉산리', '상리', '서창리', '신안리', '신흥리', '원리', '정리', '죽림리', '침산리', '평리'])